export { OpsClient, CompanionError } from './ops-client';
export type { components, operations } from './wire-types';
export {
  isCompatibleApiVersion,
  EXPECTED_API_VERSION,
} from './types';
export type {
  HealthData,
  HealthMeta,
  HealthResponse,
  CompanionVersionInfo,
  PairStartData,
  PairStartResponse,
  PairRecoveryStartResponse,
  PairConfirmRequest,
  PairConfirmData,
  PairConfirmResponse,
  PairStatusResponse,
  PairRevokeData,
  PairRevokeResponse,
  HHStatusResponse,
  HHSearchProfile,
  HHSearchProfilesResponse,
  HHSearchProfileResponse,
  HHSearchPreviewResponse,
  HHVacancySyncResponse,
  CompanionErrorData,
  CompanionErrorResponse,
  CompanionStatus,
} from './types';
export type {
  VacancyIntakeV1,
  VacancyIntakeData,
  VacancyIntakeResponse,
  VacancyListItem,
  VacancyListMeta,
  VacancyListFilters,
  VacancyListResponse,
  VacancyDetailResponse,
  VacancyTriageRequest,
  VacancyTriageRiskFlag,
  VacancyTriageHardGate,
  VacancyTriageComponent,
  VacancyTriageData,
  VacancyTriageResponse,
} from './vacancy-types';
