export { OpsClient, CompanionError } from './ops-client';
export {
  isCompatibleApiVersion,
  EXPECTED_API_VERSION,
} from './types';
export type {
  HealthData,
  HealthMeta,
  HealthResponse,
  CompanionVersionInfo,
  PairStartData,
  PairStartResponse,
  PairConfirmRequest,
  PairConfirmData,
  PairConfirmResponse,
  PairRevokeData,
  PairRevokeResponse,
  HHStatusResponse,
  HHSearchProfile,
  HHSearchProfilesResponse,
  HHSearchProfileResponse,
  HHVacancySyncResponse,
  CompanionErrorData,
  CompanionErrorResponse,
  CompanionStatus,
} from './types';
export type {
  VacancyIntakeV1,
  VacancyIntakeData,
  VacancyIntakeResponse,
  VacancyListItem,
  VacancyListMeta,
  VacancyListResponse,
  VacancyDetailResponse,
  VacancyTriageRequest,
  VacancyTriageRiskFlag,
  VacancyTriageHardGate,
  VacancyTriageComponent,
  VacancyTriageData,
  VacancyTriageResponse,
} from './vacancy-types';
