"""initial domain schema

Revision ID: 9f6dc2bb4869
Revises:
Create Date: 2026-07-29 23:43:01.789783
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f6dc2bb4869'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'hh_accounts',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('hh_user_id', sa.String(), nullable=True),
        sa.Column('display_name', sa.String(), nullable=True),
        sa.Column('connected', sa.Boolean(), nullable=False),
        sa.Column('capabilities_json', sa.String(), nullable=True),
        sa.Column('last_sync_at', sa.String(), nullable=True),
        sa.Column('revision', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.Column('updated_at', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('hh_user_id'),
    )
    op.create_table(
        'hh_sync_runs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('sync_type', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('items_seen', sa.Integer(), nullable=True),
        sa.Column('items_created', sa.Integer(), nullable=True),
        sa.Column('items_updated', sa.Integer(), nullable=True),
        sa.Column('error_summary', sa.String(), nullable=True),
        sa.Column('started_at', sa.String(), nullable=False),
        sa.Column('finished_at', sa.String(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'partial', 'error')", name='ck_sync_run_status'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'search_profiles',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('query_json', sa.String(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('schedule', sa.String(), nullable=True),
        sa.Column('last_run_at', sa.String(), nullable=True),
        sa.Column('revision', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.Column('updated_at', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'settings',
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value_json', sa.String(), nullable=False),
        sa.Column('revision', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.Column('updated_at', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('key'),
    )
    op.create_table(
        'vacancies',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('source_vacancy_id', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('company_id', sa.String(), nullable=True),
        sa.Column('company_name', sa.String(), nullable=True),
        sa.Column('salary_min', sa.Float(), nullable=True),
        sa.Column('salary_max', sa.Float(), nullable=True),
        sa.Column('currency', sa.String(), nullable=True),
        sa.Column('work_mode', sa.String(), nullable=True),
        sa.Column('experience', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('description_hash', sa.String(), nullable=True),
        sa.Column('skills_json', sa.String(), nullable=True),
        sa.Column('first_seen_at', sa.String(), nullable=False),
        sa.Column('last_seen_at', sa.String(), nullable=False),
        sa.Column('updated_at', sa.String(), nullable=False),
        sa.Column('archived', sa.Boolean(), nullable=False),
        sa.Column('revision', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('source', 'source_vacancy_id', name='uq_vacancy_source'),
    )
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.create_index(
            'ix_vacancies_source_id', ['source', 'source_vacancy_id'], unique=False
        )

    op.create_table(
        'applications',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('vacancy_id', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('decision', sa.String(), nullable=True),
        sa.Column('score', sa.Float(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('primary_proof', sa.String(), nullable=True),
        sa.Column('selected_profile_id', sa.String(), nullable=True),
        sa.Column('selected_resume_id', sa.String(), nullable=True),
        sa.Column('applied_at', sa.String(), nullable=True),
        sa.Column('next_action_at', sa.String(), nullable=True),
        sa.Column('revision', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.Column('updated_at', sa.String(), nullable=False),
        sa.CheckConstraint(
            "status IN ('new', 'viewed', 'saved', 'rejected_by_me', "
            "'letter_ready', 'applied', 'hr_replied', 'interview', "
            "'test_task', 'rejected_by_company', 'offer', 'blacklist')",
            name='ck_application_status',
        ),
        sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'engine_runs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('vacancy_id', sa.String(), nullable=False),
        sa.Column('engine_version', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('model', sa.String(), nullable=True),
        sa.Column('prompt_version', sa.String(), nullable=False),
        sa.Column('input_hash', sa.String(), nullable=False),
        sa.Column('raw_output', sa.String(), nullable=True),
        sa.Column('validated_output', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('validation_errors_json', sa.String(), nullable=True),
        sa.Column('token_input', sa.Integer(), nullable=True),
        sa.Column('token_output', sa.Integer(), nullable=True),
        sa.Column('estimated_cost', sa.Float(), nullable=True),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'success', 'invalid', 'error')",
            name='ck_engine_run_status',
        ),
        sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'vacancy_snapshots',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('vacancy_id', sa.String(), nullable=False),
        sa.Column('description_hash', sa.String(), nullable=False),
        sa.Column('payload_json', sa.String(), nullable=True),
        sa.Column('captured_at', sa.String(), nullable=False),
        sa.Column('capture_source', sa.String(), nullable=False),
        sa.Column('idempotency_key', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('idempotency_key'),
    )
    op.create_table(
        'application_events',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('application_id', sa.String(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('payload_json', sa.String(), nullable=True),
        sa.Column('occurred_at', sa.String(), nullable=False),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'cover_letters',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('application_id', sa.String(), nullable=False),
        sa.Column('mode', sa.String(), nullable=False),
        sa.Column('generated_text', sa.String(), nullable=True),
        sa.Column('sent_text', sa.String(), nullable=True),
        sa.Column('is_final', sa.Boolean(), nullable=False),
        sa.Column('revision', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.Column('updated_at', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'evidence_usage',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('engine_run_id', sa.String(), nullable=False),
        sa.Column('requirement', sa.String(), nullable=True),
        sa.Column('evidence_level', sa.String(), nullable=True),
        sa.Column('claim_id', sa.String(), nullable=True),
        sa.Column('case_id', sa.String(), nullable=True),
        sa.Column('portfolio_id', sa.String(), nullable=True),
        sa.Column('allowed_wording', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['engine_run_id'], ['engine_runs.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'followups',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('application_id', sa.String(), nullable=False),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('due_at', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('draft_text', sa.String(), nullable=True),
        sa.Column('sent_at', sa.String(), nullable=True),
        sa.Column('revision', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.Column('updated_at', sa.String(), nullable=False),
        sa.CheckConstraint("status IN ('pending', 'sent', 'skipped')", name='ck_followup_status'),
        sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'interview_packs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('application_id', sa.String(), nullable=False),
        sa.Column('engine_run_id', sa.String(), nullable=True),
        sa.Column('content_json', sa.String(), nullable=True),
        sa.Column('export_path', sa.String(), nullable=True),
        sa.Column('revision', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.Column('updated_at', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['engine_run_id'], ['engine_runs.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'letter_versions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('cover_letter_id', sa.String(), nullable=False),
        sa.Column('version_type', sa.String(), nullable=False),
        sa.Column('body_text', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=True),
        sa.Column('model', sa.String(), nullable=True),
        sa.Column('prompt_version', sa.String(), nullable=True),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.CheckConstraint(
            "version_type IN ('generated', 'imported', 'user_draft', 'final', 'sent')",
            name='ck_letter_version_type',
        ),
        sa.ForeignKeyConstraint(['cover_letter_id'], ['cover_letters.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('letter_versions')
    op.drop_table('interview_packs')
    op.drop_table('followups')
    op.drop_table('evidence_usage')
    op.drop_table('cover_letters')
    op.drop_table('application_events')
    op.drop_table('vacancy_snapshots')
    op.drop_table('engine_runs')
    op.drop_table('applications')
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_index('ix_vacancies_source_id')

    op.drop_table('vacancies')
    op.drop_table('settings')
    op.drop_table('search_profiles')
    op.drop_table('hh_sync_runs')
    op.drop_table('hh_accounts')
    # ### end Alembic commands ###
