import { spawnSync } from 'node:child_process';
import { mkdtemp, readFile, rm, writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, relative, resolve } from 'node:path';
import process from 'node:process';
import { fileURLToPath, URL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const snapshotPath = join(root, 'shared', 'contracts', 'openapi.json');
const generatedPath = join(root, 'shared', 'contracts', 'generated', 'openapi-types.ts');

const GENERATED_HEADER = `/**
 * GENERATED — DO NOT EDIT
 * Source: shared/contracts/openapi.json
 * Regenerate: pnpm contracts:generate
 *
 * This file was generated by openapi-typescript.
 */

`;

function normalizeText(value) {
  return value.replace(/\r\n?/g, '\n');
}

function generatedSafetyViolations(value) {
  const checks = [
    ['absolute Windows path', /[A-Za-z]:[\\/]/],
    ['absolute Unix home path', /\/(?:home|Users)\//],
    ['local runtime directory', /\.local(?:[\\/]|\b)/i],
    ['private engine path', /private-engine/i],
    ['runtime SQLite database', /vacancypilot\.db/i],
    ['private key material', /-----BEGIN [A-Z ]*PRIVATE KEY-----/],
    ['provider secret value', /\bsk-[A-Za-z0-9_-]{20,}\b/],
    ['nondeterministic ISO timestamp', /\b20\d{2}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z\b/],
  ];
  return checks.filter(([, pattern]) => pattern.test(value)).map(([name]) => name);
}

async function renderGenerated() {
  const source = await readFile(snapshotPath, 'utf8');
  const document = JSON.parse(source);
  const ast = await openapiTS(document);
  return normalizeText(`${GENERATED_HEADER}${astToString(ast)}`).replace(/\n+$/, '\n');
}

function runOpenApiSnapshotCheck() {
  const result = spawnSync(
    'uv',
    ['run', '--project', 'companion', 'python', '-m', 'app.openapi', '--check'],
    { cwd: root, encoding: 'utf8' },
  );
  if (result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);
  if (result.error) {
    throw new Error(`Could not run the FastAPI OpenAPI check: ${result.error.message}`);
  }
  if (result.status !== 0) {
    throw new Error('FastAPI runtime OpenAPI does not match shared/contracts/openapi.json');
  }
}

async function compareGenerated(tracked, generated) {
  const temporaryDirectory = await mkdtemp(join(tmpdir(), 'vacancypilot-contract-'));
  const temporaryPath = join(temporaryDirectory, 'openapi-types.ts');
  try {
    await writeFile(temporaryPath, generated, 'utf8');
    const temporary = normalizeText(await readFile(temporaryPath, 'utf8'));
    return normalizeText(tracked) === temporary;
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
}

async function generate() {
  const generated = await renderGenerated();
  const violations = generatedSafetyViolations(generated);
  if (violations.length > 0) {
    throw new Error(`Generated contract failed safety checks: ${violations.join(', ')}`);
  }
  await mkdir(dirname(generatedPath), { recursive: true });
  const current = await readFile(generatedPath, 'utf8').catch(() => null);
  if (current !== generated) {
    await writeFile(generatedPath, generated, 'utf8');
  }
  process.stdout.write(`Generated ${relative(root, generatedPath)}\n`);
}

async function check() {
  if (!(await readFile(snapshotPath, 'utf8').catch(() => null))) {
    throw new Error(`Missing canonical OpenAPI snapshot: ${relative(root, snapshotPath)}`);
  }
  runOpenApiSnapshotCheck();

  const generated = await renderGenerated();
  const secondGeneration = await renderGenerated();
  if (generated !== secondGeneration) {
    throw new Error('OpenAPI → TypeScript generation is not deterministic');
  }
  const violations = generatedSafetyViolations(generated);
  if (violations.length > 0) {
    throw new Error(`Generated contract failed safety checks: ${violations.join(', ')}`);
  }

  const tracked = await readFile(generatedPath, 'utf8').catch(() => null);
  if (tracked === null) {
    throw new Error(`Missing generated TypeScript contract: ${relative(root, generatedPath)}`);
  }
  if (!(await compareGenerated(tracked, generated))) {
    throw new Error(
      `Generated TypeScript contract drift detected: ${relative(root, generatedPath)}. ` +
        'Run pnpm contracts:generate.',
    );
  }
  process.stdout.write(
    `Contracts are current and deterministic: ${relative(root, generatedPath)}\n`,
  );
}

const command = process.argv[2];
if (command === 'generate') {
  await generate();
} else if (command === 'check') {
  await check();
} else {
  process.stderr.write('Usage: node scripts/contracts.mjs <generate|check>\n');
  process.exitCode = 2;
}
